2020-02-20 12:06:41,823 ERROR: Exception on /explore2 [GET] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 132, in explore2
    page, app.config['POSTS_PER_PAGE'], False)
NameError: name 'app' is not defined
2020-02-20 12:07:53,652 ERROR: Exception on /simple [GET] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 145, in simple
    form = EmpForm()
NameError: name 'EmpForm' is not defined
2020-02-20 12:10:43,302 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
2020-02-20 12:13:12,262 ERROR: Exception on /simple [GET] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 145, in simple
    form = EmpForm()
NameError: name 'EmpForm' is not defined
2020-02-20 12:16:23,932 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
2020-02-20 12:18:31,900 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
2020-02-20 12:35:11,491 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
2020-02-20 12:39:25,398 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
2020-02-20 12:39:48,685 ERROR: Exception on /edit [POST] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 161, in edit
    employee = Employee(name=form.name.data, email=form.email.data, employeeid = form.employeeid.data, ProductGroup = form.ProductGroup.data )
AttributeError: 'EmpForm1' object has no attribute 'name'
2020-02-20 12:43:53,213 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
2020-02-20 12:44:32,238 ERROR: Exception on /edit [POST] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 161, in edit
    employee = Employee(name=form.name.data, email=form.email.data, employeeid = form.employeeid.data, ProductGroup = form.ProductGroup.data )
AttributeError: 'EmpForm1' object has no attribute 'name'
2020-02-20 12:47:16,003 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
2020-02-20 12:47:57,349 ERROR: Exception on /edit [POST] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 161, in edit
    employee = Employee(employeeid=form.employeeid.data, sectorranknew = form.sectorranknew.data, comments = form.comments.data )
AttributeError: 'EmpForm1' object has no attribute 'sectorranknew'
2020-02-20 12:48:27,176 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:74]
