2020-03-11 19:38:20,466 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-11 19:39:00,383 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-11 19:44:23,181 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-11 19:44:31,255 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-11 20:11:35,107 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:05:56,914 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:06:22,776 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:10:18,732 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:11:28,149 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:11:58,061 ERROR: Exception on /export_posts [GET] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 206, in export_posts
    current_user.launch_task('export_posts', _('Exporting posts...'))
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\models.py", line 152, in launch_task
    rq_job = current_app.task_queue.enqueue('app.tasks.' + name, self.id,
NameError: name 'current_app' is not defined
2020-03-14 07:14:13,337 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:15:11,289 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:31:47,173 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:34:41,681 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:48:43,090 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-14 07:50:14,725 ERROR: Exception on /export_posts [GET] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 206, in export_posts
    current_user.launch_task('export_posts', _('Exporting posts...'))
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\models.py", line 152, in launch_task
    rq_job = current_app.task_queue.enqueue('app.tasks.' + name, self.id,
NameError: name 'current_app' is not defined
2020-03-16 20:43:27,677 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-16 20:43:43,132 ERROR: Exception on /export_posts [GET] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 206, in export_posts
    current_user.launch_task('export_posts', _('Exporting posts...'))
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\models.py", line 152, in launch_task
    rq_job = current_app.task_queue.enqueue('app.tasks.' + name, self.id,
NameError: name 'current_app' is not defined
2020-03-16 21:03:46,487 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-20 20:50:51,381 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-20 20:55:19,459 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-20 20:55:58,080 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-22 14:57:27,447 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-22 14:59:47,636 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-22 15:03:27,212 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-22 15:08:34,015 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-22 15:10:28,516 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-22 15:10:31,905 ERROR: Exception on /translate [POST] [in c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\lovellwi\pycharmprojects\microblog\venv\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\main\routes.py", line 176, in translate_text
    return jsonify({'text': translate(request.form['text'],
  File "C:\Users\LovellWi\PycharmProjects\microblog\app\translate.py", line 12, in translate
    'Ocp-Apim-Subscription-Key': [c70fd239cd4c4952bbc6201bd3c01b0f]}
NameError: name 'c70fd239cd4c4952bbc6201bd3c01b0f' is not defined
2020-03-22 15:10:53,973 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-22 15:17:06,970 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:83]
2020-03-22 15:57:38,200 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\microblog\app\__init__.py:82]
2020-03-28 10:01:47,917 INFO: Microblog startup [in C:\Users\LovellWi\PycharmProjects\Master Talent Template\app\__init__.py:82]
